# Default values for node-webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

webapp:
  name: web
  run: web
  namespace: default
  containerPort: 8080
  protocol: TCP

image:
  repository: bilalahmad99/node-webapp
  tag: latest
  pullPolicy: Always

service:
  name: web
  run: web
  namespace: default
  type: NodePort
  port: 8080
  targetPort: 8080

autoscale:
  minReplica: 1
  maxReplica: 5
  cpuTargetAvgUtil: 80

ingress:
  enabled: true
  name: basic-ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
